[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
